// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/guregu/null"
)

type Board struct {
	ID        uint32      `db:"id" json:"id"`
	UserID    uint64      `db:"user_id" json:"user_id"`
	Title     null.String `db:"title" json:"title"`
	SortOrder uint32      `db:"sort_order" json:"sort_order"`
	CreatedAt null.Time   `db:"created_at" json:"created_at"`
	UpdatedAt null.Time   `db:"updated_at" json:"updated_at"`
}

type Status struct {
	ID        uint32      `db:"id" json:"id"`
	BoardID   uint32      `db:"board_id" json:"board_id"`
	Title     null.String `db:"title" json:"title"`
	SortOrder uint32      `db:"sort_order" json:"sort_order"`
	CreatedAt null.Time   `db:"created_at" json:"created_at"`
	UpdatedAt null.Time   `db:"updated_at" json:"updated_at"`
}

type Ticket struct {
	ID          uint64      `db:"id" json:"id"`
	StatusID    uint32      `db:"status_id" json:"status_id"`
	Title       null.String `db:"title" json:"title"`
	Description null.String `db:"description" json:"description"`
	Contact     null.String `db:"contact" json:"contact"`
	SortOrder   uint32      `db:"sort_order" json:"sort_order"`
	CreatedAt   null.Time   `db:"created_at" json:"created_at"`
	UpdatedAt   null.Time   `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        uint64      `db:"id" json:"id"`
	Name      null.String `db:"name" json:"name"`
	Lastname  null.String `db:"lastname" json:"lastname"`
	Email     null.String `db:"email" json:"email"`
	Password  null.String `db:"password" json:"password"`
	CreatedAt null.Time   `db:"created_at" json:"created_at"`
	UpdatedAt null.Time   `db:"updated_at" json:"updated_at"`
}
