// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Board struct {
	ID        uint32
	UserID    uint64
	Title     sql.NullString
	SortOrder uint32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Status struct {
	ID        uint32
	BoardID   uint32
	Title     sql.NullString
	SortOrder uint32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Ticket struct {
	ID          uint64
	StatusID    uint32
	Title       sql.NullString
	Description sql.NullString
	Contact     sql.NullString
	SortOrder   uint32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID        uint64
	Name      sql.NullString
	Lastname  sql.NullString
	Email     sql.NullString
	Password  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
