// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO
  users (name, lastname, email, password, created_at)
VALUES
  (?, ?, ?, ?, NOW())
`

type CreateUserParams struct {
	Name     sql.NullString
	Lastname sql.NullString
	Email    sql.NullString
	Password sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Lastname,
		arg.Email,
		arg.Password,
	)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
  id, name, lastname, email, password, created_at, updated_at
FROM
  users
WHERE
  email = ?
LIMIT
  1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
  id, name, lastname, email, password, created_at, updated_at
FROM
  users
WHERE
  id = ?
LIMIT
  1
`

func (q *Queries) GetUser(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE
  users
SET
  name = ?,
  lastname = ?,
  email = ?,
  password = ?,
  updated_at = NOW()
WHERE
  id = ?
`

type UpdateUserParams struct {
	Name     sql.NullString
	Lastname sql.NullString
	Email    sql.NullString
	Password sql.NullString
	ID       uint64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Lastname,
		arg.Email,
		arg.Password,
		arg.ID,
	)
	return err
}
