services:
  gateway:
    image: gateway:development
    build:
      context: .
      dockerfile: ./build/gateway/Dockerfile.dev
    ports:
      - "3999:3999"
    volumes:
      - ./cmd/gateway:/app/cmd/gateway
      - ./api/gateway:/app/api/gateway
      - ./pkg:/app/pkg
  authen:
    image: authen:development
    build:
      context: .
      dockerfile: ./build/authen/Dockerfile.dev
    ports:
      - "4000"
    volumes:
      - ./cmd/authen:/app/cmd/authen
      - ./api/authen:/app/api/authen
      - ./pkg:/app/pkg
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: ./build/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ticket_dev
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: randomrootpassword
    ports:
      - "3306:3306"
