services:
  authen:
    build:
      context: .
      dockerfile: ./docker/authen/Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: 5000
    ports:
      - "5000:5000"
  ticket:
    build:
      context: .
      dockerfile: ./docker/ticket/Dockerfile
    environment:
      PORT: 5001
    ports:
      - "5001:5001"
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    command: "pnpm run dev"
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
