services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ./build/gateway/Dockerfile.dev
    ports:
      - "3999:3999"
    volumes:
      - ./cmd/gateway:/app/cmd/gateway
      - ./api/gateway:/app/api/gateway
      - ./pkg:/app/pkg
  authen:
    image: authen
    build:
      context: .
      dockerfile: ./build/authen/Dockerfile.dev
    expose:
      - "4000"
    ports:
      - "4000"
    volumes:
      - ./cmd/authen:/app/cmd/authen
      - ./api/authen:/app/api/authen
      - ./pkg:/app/pkg
    depends_on:
      - mysql
  client:
    build:
      context: ./client2
      dockerfile: Dockerfile
    command: pnpm run dev
    volumes:
      - ./client2:/app
    ports:
      - "3000:3000"
  mysql:
    build:
      context: .
      dockerfile: ./build/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ticket_dev
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: randomrootpassword
    expose:
      - "3306"
    ports:
      - "3306:3306"
