services:
  gateway:
    host: 0.0.0.0
    port: 3999
    url: http://localhost:3999
  authen:
    host: 0.0.0.0
    port: 4000
    url: http://authen:4000
  ticket:
    host: 0.0.0.0
    port: 4001
    url: http://ticket:4001
  client:
    host: 0.0.0.0
    port: 3000
    url: http://localhost:3000
  database:
    host: "mysql"
    dbname: "ticket_dev"
    user: "root"
    password: "randomrootpassword"
private_key: "/app/certs/private_key.pem"
public_key: "/app/certs/public_key.pem"
access_token_expire: 3600
refresh_token_expire: 86400
