
FROM cosmtrek/air AS builder

WORKDIR /app

COPY . .
COPY air/gateway ./

# delete unnecessary files
RUN rm -rf client
RUN rm -rf docker

FROM cosmtrek/air AS runtime

WORKDIR /app

COPY --from=builder /app .
COPY --from=builder /app/.air.toml .

CMD ["air", "-c", ".air.toml"]