
FROM cosmtrek/air AS builder

WORKDIR /app

COPY . .

# delete unnecessary files
RUN rm -rf client
RUN rm -rf docker

FROM cosmtrek/air AS runtime

WORKDIR /app

COPY --from=builder /app .

RUN go mod download

WORKDIR /app/cmd/gateway

RUN air init

CMD ["air", "-c", ".air.toml"]